services:
  - type: web
    name: unified-medical-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir=unified-medical-system run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
