services:
  - type: web
    name: unified-medical-system
    env: python
    buildCommand: cd unified-medical-system && pip install -r requirements.txt
    startCommand: cd unified-medical-system && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
